---
sudo: required
# docker is required to run tests
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test

notifications:
  slack:
    secure: Drdq7YdqASd4szTJqGNuytHDXWzsKWjL3amtS7M89teYbp9Ou5x+neAABlHFiQEkrfVKuQEtVUg84OzXpVYz5SmmkFrElYHwzRsPezEffr6UZEhpoC+5xnCXjPO+1DP4erXwEm1CBxWJHQNDBtl6KpCLA5lkrFktCNLkOQyCHfl1WiA/UyNEoX/U1XVdIMQtSXz2rSbYa/n3EObp50kuRVN8dju5BfARfAlOJOOd7Q3ObNs9fUHZsJYyGOHpngCdAMq0xePMbcwrcn9ozrfkqicTIv0HzAnVeUHYORnlf536rpqyGzOrVoz6tPVzYBiWj6WP5IQcFs8bpUqK+b8C7gDLnfzFabZf9kpmioJELffRH4HtOG+BR1QPFlWY+tpl12vPj1+5Xz8ay691FyFSsnhgY84g+7ToYZFg8I8Xnu9WCFyTZOlxchyWD+Ia+YEg/qgHxEMu09w5VGN4G2gAxzeFtF1iaJCXBW72pZyhVYrTuKtbiB62EW9YwPhHz7tl0FyP6/W0b5Otoc5p6S4I26eofZ2DeahyajXZropiXbUmoRkFScAVRZXGAaCbAImfe6e4BNmg+CRp3J3D+4LnsGSt1PQseXhoda0KcOeR1CAtHfqiGPjPJYzh5NVvSmCSG5g3rIRPiXxrWvv07zymF+jXTEST5Y1Zb1FjjbjvO1w=
