---
- name: create pagespeed folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/tmp/ngx_pagespeed-release-{{ nginx_pagespeed_version }}-beta"

- name: download pagespeed
  unarchive:
    src: "{{ item }}"
    dest: /tmp
    copy: no
  with_items:
    - "https://github.com/pagespeed/ngx_pagespeed/archive/release-{{ nginx_pagespeed_version }}-beta.zip"

- name: download pagespeed
  unarchive:
    src: "{{ item }}"
    dest: /tmp/ngx_pagespeed-release-{{ nginx_pagespeed_version }}-beta
    copy: no
  with_items:
    - "https://dl.google.com/dl/page-speed/psol/{{ nginx_pagespeed_version }}.tar.gz"
