---
- name: "Directory Exists | {{ nginx_log_root }}"
  file:
    state: directory
    path: "{{ nginx_log_root }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0775
  tags:
    - directory-structure
    - logging
    - nginx
